#pragma once

#include "../Types.h"

#include <span>
#include <string_view>

namespace bud::factory
{

/** What each instrument offers, by name.

    The SOUND parameter is a 0-127 knob over a bank that wraps, which is faithful to the device
    and useless to look at: nothing tells you what 43 is. This is the shortlist that sits in
    front of it — five named sounds per track, chosen to be five *different* drums rather than
    five settings of one.

    The sounds themselves are the signature slots at the head of each factory bank, generated by
    FactoryContent. This table only says which of them a given track offers and what to call
    them, so a track's menu and the audio behind it cannot drift apart.

    Selecting an entry sets the track's BANK and SOUND parameters; nothing else is stored. The
    knob still reaches every sound in the bank, so the menu is a shortcut rather than a limit.
*/
struct SoundChoice
{
    std::string_view name;    ///< What the interface shows
    SoundBank bank;           ///< Value for ParamKind::TrackSoundBank
    int sound;                ///< Value for ParamKind::TrackSound
};

/// Every track offers this many.
inline constexpr int kSoundsPerTrack = 5;

/// The sounds offered for a track, or an empty span if the track index is out of range.
std::span<const SoundChoice> soundMenu (int track) noexcept;

/// Which entry a track's current bank and sound correspond to, or -1 when the knob has been
/// moved somewhere the menu does not name.
int menuIndexFor (int track, SoundBank bank, int sound) noexcept;

} // namespace bud::factory
