#pragma once

#include "../Types.h"

#include <algorithm>
#include <array>
#include <string>
#include <vector>

namespace bud
{

/// User sample banks. Slot counts and lengths follow the device (p. 67, 116).
constexpr int userSlotCount (SoundBank bank) noexcept
{
    switch (bank)
    {
        case SoundBank::S2: return 32;
        case SoundBank::S4: return 16;
        case SoundBank::S8: return 12;
        default:            return 0;
    }
}

constexpr double userMaxSeconds (SoundBank bank) noexcept
{
    switch (bank)
    {
        case SoundBank::S2: return 2.0;
        case SoundBank::S4: return 4.0;
        case SoundBank::S8: return 8.0;
        default:            return 0.0;
    }
}

/// Only the loop bank is stereo.
constexpr bool userBankIsStereo (SoundBank bank) noexcept { return bank == SoundBank::S8; }

//==============================================================================

/** One sound: a block of audio plus what the engine needs to play it musically.

    Audio is held as float at whatever rate it was loaded with. The device records and exports
    48 kHz / 16-bit linear PCM, which is what import and export use, but keeping the working
    copy in float avoids requantising on every edit.
*/
struct SampleData
{
    std::vector<float> left;
    std::vector<float> right;   ///< Empty for mono
    double sampleRate = 48000.0;
    std::string name;

    /// Musical length of the recorded material, when known. Drives repitch- and
    /// stretch-to-tempo.
    double sourceBeats = 0.0;

    bool isStereo() const noexcept { return ! right.empty(); }
    bool empty() const noexcept { return left.empty(); }
    int length() const noexcept { return static_cast<int> (left.size()); }

    void clear()
    {
        left.clear();
        right.clear();
        name.clear();
        sourceBeats = 0.0;
    }

    /// Reads a channel with bounds checking, so voices can interpolate past the end safely.
    float at (int channel, int index) const noexcept
    {
        if (index < 0 || index >= length())
            return 0.0f;

        const auto& data = (channel > 0 && isStereo()) ? right : left;
        return data[static_cast<std::size_t> (index)];
    }
};

//==============================================================================

/** All the instrument's sound content, factory and user, behind one lookup.

    The drum engine is sample-based for every bank except BD on track 1 and SD on track 3
    (p. 60), so the factory banks are not an optional extra — they are what most of the
    instrument plays. They are generated by tools/factory_gen rather than shipped as audio.

    S2, S4 and S8 route to the user sample banks; every other bank routes to the factory set.
*/
class SoundLibrary
{
public:
    SoundLibrary();

    /// The sound at an index within a bank, or nullptr when the slot is empty or out of range.
    const SampleData* find (SoundBank bank, int index) const noexcept;

    /// Number of sounds available in a bank.
    int count (SoundBank bank) const noexcept;

    //==========================================================================
    // Factory content

    std::vector<SampleData>& factory (SoundBank bank) noexcept
    {
        return factory_[static_cast<std::size_t> (bank)];
    }

    const std::vector<SampleData>& factory (SoundBank bank) const noexcept
    {
        return factory_[static_cast<std::size_t> (bank)];
    }

    //==========================================================================
    // User sample banks

    SampleData& userSlot (SoundBank bank, int index) noexcept;
    const SampleData& userSlot (SoundBank bank, int index) const noexcept;

    void clearAll();

private:
    static int userBankIndex (SoundBank bank) noexcept;

    std::array<std::vector<SampleData>, kNumSoundBanks> factory_ {};
    std::array<std::vector<SampleData>, 3> user_ {};   ///< S2, S4, S8
    SampleData empty_;
};

} // namespace bud
